# Numpy Introduction

## What is NumPy? 

- NumPy or Numerical Python is a Python library used for working with arrays. Arrays are very frequently used in data science, where speed and resources are very important.

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- NumPy is an open source project and you can use it freely.

## Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Applications of NumPy
- Mathematics
- Plotting (Matplotlib)
- Backend (Pandas)
- Machine Learning 

## First Example - Initializing an 1D-array 

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`. We can create a NumPy `ndarray`object using the `array()` function.

In [1]:
import numpy 

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


`Observation:` NumPy is usually imported under the `np` alias. Alias in Python are an alternate name for referring to the same thing.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### Checking NumPy Version

In [3]:
print(np.__version__)

1.26.4


## 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [4]:
arr = np.array(42)

print(arr)

42


## 2-D Arrays

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D Arrays

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## How to Check the Number of Dimensions? 
NumPy Arrays provides `ndim` attribute that returns an integer that tells us how many dimensions the array have. 

In [7]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## How to Get the Shape?
The shape is an attribute in NumPy that returns a tuple representing the dimensions of the array. It describes how many elements are along each dimension (axis) of the array.

In [8]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(1, 3, 3)


## Reshaping Arrays

In [9]:
# 2D to 1D 
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]


In [10]:
# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


`Observation:` We can reshape into any shape as long as the elements required for reshaping are equal in both shapes. For example, we can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [12]:
# Error 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass `-1` as the value, and NumPy will calculate this number for you.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, -1, 3)  
print(newarr)
print()
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

(2, 2, 3)


### Flattening the arrays 
Flattening array means converting a multidimensional array into a 1D array.
We can use `reshape(-1)`

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## Acess Array Elements

### 1-D Array

In [16]:
arr = np.array([1, 2, 3, 4])

print(arr[0]) # 1

print(arr[2] + arr[3]) # 7

1
7


### 2-D Array
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


### 3-D Array

In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

6


#### Let's understand...

The `first number` represents the __first dimension__, which contains two arrays:  

[[1, 2, 3], [4, 5, 6]]   and  [[7, 8, 9], [10, 11, 12]]

Since we selected `0`, we have:  

[[1, 2, 3], [4, 5, 6]]

The `second number` represents the __second dimension__, which also contains two arrays:

[1, 2, 3] and [4, 5, 6]

Since we selected `1`, we have: 

[4, 5, 6]

The `third number` represents the third dimension, which contains three values: 
4
5 
6 

Since we selected `2`, we end up with the third value: __6__

### Negative Indexing

In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Slicing Arrays

- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: `[start:end]`.

- We can also define the step, like this: `[start:end:step]`.

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


`Observation`: Use the minus operator to refer to an index from the end.

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


### Step

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [28]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [29]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Checking the Data Type of an Array

The NumPy array object has a property called `dtype`that returns the data type of the array: 

In [30]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [31]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type
We use the `array()`function to create arrays, this function cant ake an optional argument: `dtype` that allows us to define the expected data type of the array elements.

In [32]:
#Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
#Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method.

The `astype()` function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.'

In [34]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [35]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [36]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [37]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]


## The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view. 

### COPY - `copy()`

In [38]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### VIEW - `view()`

In [39]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### Check if Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that __returns `None` if the array owns the data__.

Otherwise, the `base`  attribute refers to the original object.

In [41]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Iterating Arrays
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

In [42]:
# 1D Array
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [43]:
# 2D Array - printing the matrix
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [44]:
# 2D Array - Returning the scalars
# we have to iterate the arrays in each dimension.
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [45]:
# 3D Array - printing the matrix

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [46]:
# 3D Array - Returning the scalars
# we have to iterate the arrays in each dimension.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using `nditer()`
The function `nditer()`is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element
In basic `for` loops, iterating through each scalar of an array we need to use _n_ for loops which can be difficult to write for arrays with very high dimensionality.

In [47]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Iterating Array With Different Data Types
We can use `op_dtypes`argument and pass it the expected datatype to change the datatype of elements while iterating. 

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()`we pass `flags['buffered']`

In [48]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


### Iterating With Different Step Size

In [49]:
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


### Enumerated Iteration Using `ndenumerate()`

Enumeration means mentioning sequence number of somethings one by one. Sometimes we require corresponding index of the element while iterating, the `ndenumerate()` method can be used for those usecases.

In [50]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [51]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Joining NumPy Arrays 

Joining means putting contents of two or more arrays in a single array.

In SQL we joing tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the `concatenate()`function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [53]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [54]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


_2D Array:_

`axis=0`: Concatenates along the rows (vertically, one below the other).  
`axis=1`: Concatenates along the columns (horizontally, side by side).

## Joining Arrays Using Stack Functions

Stacking is same as concatenation, __the only difference is that stacking is done along a new axis__. We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking. We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0.

In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [56]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Rows - `hstack()`



In [57]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns - `vstack()`

In [58]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth) - `dstack()`

In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Splitting NumPy Arrays

__Splitting is reverse operation of Joining__. Joining merges multiple arrays into one and Splitting breaks one array into multiple. We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits.

In [60]:
#Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


`Observation:` If the array has less elements than required, it will adjust from the end accordingly.

In [61]:
# Split the array in 4 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])

[1 2]


In [63]:
arr = np.array(['a', 'b', 'c'])
newarr = np.array_split(arr, 3)
print(newarr)

[array(['a'], dtype='<U1'), array(['b'], dtype='<U1'), array(['c'], dtype='<U1')]


### Splitting 2D Arrays

In [64]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

# This example returns three 2-D arrays.
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [65]:
# Split the 2-D array into three 2-D arrays
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


You can specify which axis you want to do the split around:

The example below also returns three 2-D arrays, but they are split along the row (axis=1).

In [66]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Searching Arrays
You can search an array for a certain value, and __return the indexes that get a match__. To search an array, use the `where()` method.

In [68]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0) # even numbers

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1) # odd numbers

print(x)

(array([0, 2, 4, 6], dtype=int64),)


### Search Sorted - `searchsorted()`

There is a method called `searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

- can be used to find where specifed elements belong in the array.

In [71]:
#Find the indexes where the value 7 should be inserted
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)

print(x)

1


 The number 7 should be inserted on index 1 to remain the sort order. The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

By default the left most index is returned, but we can give `side='right'` to return the right most index instead.

In [72]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')

print(x)

2


The number 7 should be inserted on index 2 to remain the sort order.

The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

### Multiples Values

In [73]:
# Find the indexes where the values 2, 4, and 6 should be inserted
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Sorting Arrays

Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence thata has an order corresponding to elements, like numeric or alphabetical, ascending or descending. 

* The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [74]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


`Observation:` This method returns a copy of the array, leaving the original array unchanged.

In [75]:
print(arr)

[3 2 0 1]


In [76]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [77]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [78]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering. In NumPy, we filter an array using a boolean index list.

* A boolean index list is a list of booleans corresponding to indexes in the array.
* If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [79]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


### Creating the Filter Array

In [80]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


#### Creating a Filter Directly From Array

In [81]:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
